project_name: 火脸服务商后台
env: 预发环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name:  小     熊

# 域名1
host: https://api.pre.lianok.com
# 域名2，支持多个域名配置
#app_host:

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
notification_type: 4
# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
#excel_report: False

## 钉钉相关配置
#ding_talk:
##  webhook:
##  secret:
#  webhook:
#  secret:
## 数据库相关配置
mysql_db:
# 数据库开关
  switch: True
  host: 121.41.215.125
#生产 ：java-lianok.mysql.polardb.rds.aliyuncs.com
  user: root
#生产：readyonly
  password: Youyun@baisi
#生产： m4HSaAlQVzoK%bj7Z$zH3UlpJpR6t0
  port: 3306
## 镜像源
#mirror_source: http://mirrors.aliyun.com/pypi/simple/
## 企业通知的相关配置
#wechat:
#  webhook:
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!

email:
  send_user: mys
  email_host: huolianpro.com
#  # 自己到QQ邮箱中配置stamp_key
#  stamp_key:
  # 收件人改成自己的邮箱
  send_list: mys@huolianpro.com
# 飞书通知
lark:
  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/77e9d07c-8eb3-478c-adb9-9384797f14b4
